(()=>{'use strict';const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let editing=null;const habits=()=>Store.getHabits(),date=()=>Store.todayStr(),logs=()=>{try{return JSON.parse(localStorage.getItem('readiness:habitLogs')||'{}')}catch{return {}}};const eligible=(h,d)=>!h.schedule||h.schedule.includes(String(d.getDay()));const achieved=(h,v)=>h.type==='binary'?v===true:v!==null&&Number(v)>=(Number(h.target)||1);function range(h,n){let due=0,done=0,recorded=0;const end=new Date(date());for(let i=n-1;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);if(!eligible(h,d))continue;due++;const v=logs()[Store.todayStr(d)]?.[h.id]??null;if(v!==null)recorded++;if(achieved(h,v))done++;}return{due,done,recorded,pct:due?Math.round(done/due*100):0};}
function render(){const hs=habits(),n=+$('period').value;let due=0,done=0;const stats=hs.map(h=>({h,...range(h,n)}));stats.forEach(x=>{due+=x.due;done+=x.done});$('summaryStats').innerHTML=[['Tingkat tercapai',due?Math.round(done/due*100)+'%':'—'],['Hari terjadwal',due],['Kebiasaan aktif',hs.length]].map(([a,b])=>'<div class="summary-stat"><small>'+a+'</small><strong>'+b+'</strong></div>').join('');
$('habitRows').innerHTML=stats.length?stats.map(x=>'<article class="summary-habit"><div class="summary-habit-top"><strong>'+esc(x.h.icon||'✦')+' '+esc(x.h.name)+'</strong><b>'+x.pct+'%</b></div><div class="summary-track"><i style="width:'+x.pct+'%"></i></div><small>'+x.done+' / '+x.due+' hari tercapai · '+x.recorded+' hari memiliki catatan</small></article>').join():'<p class="muted">Belum ada kebiasaan. Tambahkan dari halaman Hari ini.</p>';
const points=[];const end=new Date(date());for(let i=6;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);const eligibleHs=hs.filter(h=>eligible(h,d));const count=eligibleHs.filter(h=>achieved(h,logs()[Store.todayStr(d)]?.[h.id]??null)).length;points.push({label:['Min','Sen','Sel','Rab','Kam','Jum','Sab'][d.getDay()],pct:eligibleHs.length?Math.round(count/eligibleHs.length*100):0});}$('dailyChart').innerHTML=points.map(p=>'<div class="summary-day"><strong>'+p.pct+'%</strong><i style="height:'+Math.max(3,p.pct*.72)+'px"></i><small>'+p.label+'</small></div>').join('');
$('editList').innerHTML=hs.length?hs.map(h=>'<div class="summary-edit"><div><strong>'+esc(h.icon||'✦')+' '+esc(h.name)+'</strong><small>'+esc(h.type==='binary'?'Ya / Tidak':(h.target||0)+' '+(h.unit||''))+'</small></div><button class="mini-action" data-edit="'+esc(h.id)+'">Edit</button></div>').join():'<p class="muted">Tidak ada data untuk diedit.</p>';
$('editList').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(hs.find(h=>h.id===b.dataset.edit)));
const wlogs=(()=>{try{return JSON.parse(localStorage.getItem('readiness:workoutCustomLogs')||'{}')}catch{return {}}})();let completed=0,days=new Set();Object.entries(wlogs).forEach(([ds,byPlan])=>{Object.values(byPlan||{}).forEach(exs=>Object.values(exs||{}).forEach(sets=>Object.values(sets||{}).forEach(v=>{if(v===true||v?.done){completed++;days.add(ds)}})))});$('workoutSummary').innerHTML='<strong>'+completed+' set selesai</strong> pada '+days.size+' hari tercatat. <span class="muted">Rangkuman berdasarkan workout custom yang tersimpan di perangkat ini.</span>';
}
function openEdit(h){if(!h)return;editing=h.id;$('editName').value=h.name||'';$('editTarget').value=h.target??'';$('editUnit').value=h.unit||'';$('editRule').value=h.rule||'';$('editTarget').disabled=h.type==='binary';$('editModal').hidden=false;$('editName').focus();}
function close(){editing=null;$('editModal').hidden=true;}
$('period').onchange=render;$('closeEdit').onclick=close;$('cancelEdit').onclick=close;$('saveEdit').onclick=()=>{const h=habits().find(x=>x.id===editing);if(!h)return;const name=$('editName').value.trim();if(!name){$('editName').focus();return;}Store.updateHabit(editing,{name,target:h.type==='binary'?null:Math.max(0,Number($('editTarget').value)||0),unit:$('editUnit').value.trim(),rule:$('editRule').value.trim()});close();render();};render();})();